name: Publish to Test PyPI

on:
  push:
    tags:
      - 'test-v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install test dependencies
        run: |
          python -m pip install ".[test]"

      - name: Run tests
        run: |
          pytest

      - name: Install lint dependencies
        run: |
          python -m pip install ".[lint]"

      - name: Run lint
        run: |
          black --check .

      - name: Build and publish to Test PyPI
        run: |
          python -m pip install build twine
          python -m build
          twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
