name: Publish to PyPI

on:
  push:
    branches:
      - master
    tags:
      - '^v\d+\.\d+\.\d+$'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install build and test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine pytest

    - name: Run tests
      run: |
        pytest

    - name: Build and publish to PyPI
      run: |
        python -m build
        twine upload --repository pypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
