name: Publish to PyPI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .

    - name: Run tests
      run: |
        pytest

    - name: Build and publish to PyPI
      run: |
        python -m pip install build twine
        python -m build
        twine upload --repository pypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
