name: Publish to PyPI and Test PyPI

on:
  push:
    branches:
      - master
      - develop
      - test-gh-actions
    tags:
      - 'v*'
      - 'test-v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .

    - name: Run tests
      run: |
        pytest

    - name: Determine PyPI repository
      id: pypi_repository
      run: |
        if [[ $GITHUB_REF == 'refs/tags/v'* ]]; then
          echo "pypi";
        elif [[ $GITHUB_REF == 'refs/tags/test-v'* ]]; then
          echo "testpypi";
        fi
      shell: bash

    - name: Build and publish to PyPI
      if: steps.pypi_repository.outputs.pypi_repository == 'pypi'
      run: |
        python -m pip install build twine
        python -m build
        twine upload --repository pypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    - name: Build and publish to Test PyPI
      if: steps.pypi_repository.outputs.pypi_repository == 'testpypi'
      run: |
        python -m build
        twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
